"""2

Revision ID: 788bdda9838f
Revises: 3f42b72f9890
Create Date: 2024-06-30 15:15:51.540982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788bdda9838f'
down_revision: Union[str, None] = '3f42b72f9890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_role', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_role')
    # ### end Alembic commands ###
