"""1

Revision ID: d8c11dd5c97c
Revises: 
Create Date: 2024-06-29 10:59:43.878224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c11dd5c97c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('associated', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('primary', 'secondary', name='role_enum'), server_default='primary', nullable=False),
    sa.CheckConstraint('LENGTH(name) > 0', name='user_name_length_check'),
    sa.ForeignKeyConstraint(['associated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
